### ISSUE TITLE
Not subscribes

### ISSUE THREAD

**Issue by reejinbouk** [arcoirislabs/cordova-plugin-mqtt#13]
Hi
try to run demo app
successfully connect to test.mosquitto.org: 1883
also successfully publish

but when subscribe - there is no reactions for subscribed topics

in Adnroid studio i get this, when publish to subscribed topics:

I/mqttalabs: for subscribe the callback id is CordovaMqTTPlugin126837709

**Comment by arcoirislabs** [comment]
Hi,
You can start receiving the topic payload by adding a document event listener to the topic you subscribed

**Comment by arcoirislabs** [comment]
Also check if you are publishing anything on the same topic
