### ISSUE TITLE
args.success is not a function

### ISSUE THREAD

**Issue by Kradre** [arcoirislabs/cordova-plugin-mqtt#14]
Have a problem with that error, as after few minutes it forcing my whole app to crash.
Usually, error appears on 96 line of cordova-plugin-mqtt.js and 312 line of cordova.js

**Comment by arcoirislabs** [comment]
@Kradre : Thanks to notify this issue. We shall look into it and get back to you

**Comment by arcoirislabs** [comment]
The error is because there is not a check on the existence of callback function. If you want to avoid the error, then kindly add an empty function for now.
In next release we will fix this bug

Open source team
Arcoiris Labs
