### ISSUE TITLE
Cordova v5/6 support

### ISSUE THREAD

**Issue by mafabio** [arcoirislabs/cordova-plugin-mqtt#15]
Is there any development plan for that?

**Comment by arcoirislabs** [comment]
It is already working on cordova 6.x . So far we haven't received any bugs. If there are any feel free to raise an issue in the issue tracker.

Thanks 
Amey K.
Repo Maintainer

**Comment by mafabio** [comment]
Thank you for the answer. No issues at the moment,
I've just read the README documentation that claims compatibility with cordova 4 and cordova-cli 5.

**Comment by arcoirislabs** [comment]
Actually it means it is compatible with Cordova v4 and above.

**Comment by mafabio** [comment]
Ok, thanks. I'm closing the issue.
