### ISSUE TITLE
IOS ReferenceError: Can't find variable: Paho

### ISSUE THREAD

**Issue by AlekseyLeshko** [arcoirislabs/cordova-plugin-mqtt#26]
HI guys.

I build app with plugin for IOS.
When I connect to the broker I get an error
```
ReferenceError: Can't find variable: Paho
```
[client = new Paho.MQTT.Client(args.url.split("tcp://")[1], Number(args.wsPort), args.urlPath||"/ws", args.clientId);](https://github.com/arcoirislabs/cordova-plugin-mqtt/blob/master/www/cordova-plugin-mqtt.js#L110)
I use plugin v0.3.8

On Android alright work.

Thanks!

**Comment by mpfurnari** [comment]
Hi,

Attempting to write my first app using cordova, and I'm running into a similar error not finding Paho. It works for Android, but on a browser I'm getting an Uncaught ReferenceError: Paho is not defined. I tried installing a Paho plugin, but that failed. Any help would be most appreciated!

Thanks!!

**Comment by arcoirislabs** [comment]
We are releasing native iOS support

**Comment by mpfurnari** [comment]
Hi,

Any update on when IOS support will be available? I have my android app running and am ready to start testing IOS. Thanks for any help!!

Matt

**Comment by aborovsky** [comment]
Guys, any updates about iOs release? Is it ready?

**Comment by viisouza10** [comment]
Hi, 

any update about "Can't find variable: Paho" in IOS?

**Comment by rodacapera** [comment]
Hello I have the same paho error in ios, any update

**Comment by linhtranvu** [comment]
I decide to revive an old MQTT plugin, now working for BOTH IOS and Android, check here

https://github.com/linhtranvu/cordova-plugin-fastrde-mqtt
