### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by mallik-nimmagadda** [arcoirislabs/cordova-plugin-mqtt#3]
Hi... I am trying to install this plugin in Intel XDk. I was not able to install it. Have you seen any issue with installation in XDK before

Thanks,
Mallik

**Comment by arcoirislabs** [comment]
The plugin is no more in usage.
Try another one

-----Original Message-----

**Comment by arcoirislabs** [comment]
Hi,
We are pleased to announce the new and better version of the plugin. We have updated the plugin entirely to work with latest standards of Apache Cordova. 
Feel free to ping us for any issues.
Cheers.
