### ISSUE TITLE
QoS selection support

### ISSUE THREAD

**Issue by Takkuz** [arcoirislabs/cordova-plugin-mqtt#5]
Actually plugin seems to use QoS 1 without any possibility to change it. It could be great to let user to select QoS.

**Comment by arcoirislabs** [comment]
Hi Takkuz
We are rolling some new features in next release in this week. QoS selection while establishing connection and while publishing will be some of the features you may expect.
Stay tuned for the new release 

Regards,
Amey Kshirsagar
Managing Director & Co-Founder

-----Original Message-----

**Comment by Takkuz** [comment]
What a good news! You're great...
Thank you.
