### ISSUE TITLE
No javascript work with the plugin

### ISSUE THREAD

**Issue by celiandu61** [arcoirislabs/cordova-plugin-mqtt#6]
Hey, i have try to use your plugin for test but i did not succeed to etablish any connection to my mosquitto server. I have install the plugin with 
`cordova plugin add https://github.com/arcoirislabs/cordova-plugin-mqtt.git`

and use this code:

```
<script>
		cordova.plugins.CordovaMqTTPlugin.connect({
		    url:"tcp://192.168.1.11",
		    port:1883,
		    clientId:"",
		    connectionTimeout:3000,
		    willTopicConfig:{
		        qos:0,
		        retain:true,
		        topic:"remote",
		        payload:"test"
		    },
		    username:"remote",
		    password:'test',
		    keepAlive:60,
		    success:function(s){
		        alert("connect success");
		    },
		    error:function(e){
		        alert("connect error");
		    },
		    onConnectionLost:function (){
		        alert("disconnect");
		    }
		})

		cordova.plugins.CordovaMqTTPlugin.publish({
		   topic:"remote",
		   payload:"hello from the plugin",
		   qos:0,
		   retain:false
		  success:function(s){
		 
		  },
		  error:function(e){
		  
		  }
		})
    </script> 
```
When i launch my app with your plugin no javascript script work.

Thx in advance

**Comment by arcoirislabs** [comment]
Well it won't work unless you call it after the 'deviceready' event is called from cordova library.
Also you cannot publish unless the connection to the broker is successfully established.
Have you called it after the 'deviceready' event is triggered??

**Comment by celiandu61** [comment]
I have try it 
`// Wait for device API libraries to load
    //
    function onLoad() {
        document.addEventListener("deviceready", onDeviceReady, false);
    }

    // device APIs are available
    //
    function onDeviceReady() {
    	cordova.plugins.CordovaMqTTPlugin.connect({
		    url:"tcp://192.168.1.26",
		    port:1883,
		    clientId:"",
		    connectionTimeout:3000,
		    willTopicConfig:{
		        qos:0,
		        retain:true,
		        topic:"remote",
		        payload:"test"
		    },
		    username:"remote",
		    password:'remote',
		    keepAlive:60,
		    success:function(s){
		        alert("connect success");
		    },
		    error:function(e){
		        alert("connect error");
		    },
		    onConnectionLost:function (){
		        alert("disconnect");
		    }
		})

		cordova.plugins.CordovaMqTTPlugin.publish({
		   topic:"remote",
		   payload:"hello from the plugin",
		   qos:0,
		   retain:false
		  success:function(s){
		 
		  },
		  error:function(e){
		  
		  }
		})
    }`

But i have the same problem :'(

**Comment by arcoirislabs** [comment]
Have you tried to connect to a public broker?? Because it looks like you are connecting to a locally hosted server from your app. Can you check your server's firewall settings. Maybe it is not allowing the connection.
We have never faced such problem in our production apps. 

Suggestions to debug:-
1. Read the error dump from the error callback in the connect function. There you will exactly know the what is wrong.
2. Your publish function should be called from inside the success callback.
